services:
    mongodb:
        image: mongo:latest
        container_name: server
        ports:
            - "27017:27017"
        restart: always
        volumes:
            - mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin123

networks:
    default:
        driver: bridge

volumes:
    mongo:
